import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('Migración y RLS: borradores privados, publicación, jerarquía, copia y conservación de datos',async()=>{
  const db=new PGlite();
  const admin='10000000-0000-4000-8000-000000000001';
  try {
    await db.exec(`create role anon;create role authenticated;create schema auth;
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid; $$;
      grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
      create table public.administradores(user_id uuid primary key);alter table public.administradores enable row level security;
      grant select on public.administradores to authenticated;
      create policy "self" on public.administradores for select to authenticated using(user_id=auth.uid());
      insert into public.administradores values('${admin}');
      create table public.productos(id uuid primary key default gen_random_uuid(),nombre text,precio integer,stock integer);
      insert into public.productos(nombre,precio,stock) values('Producto real conservado',12345,2);`);
    for(const nombre of ['sitio-editable.sql','diseno-premium.sql']) await db.exec(await readFile(new URL('../supabase/'+nombre,import.meta.url),'utf8'));
    await db.exec("insert into public.bloques_sitio(tipo,titulo,ancla) values('texto','Contenido anterior conservado','anterior-conservado');");
    const anteriores=(await db.query('select * from public.bloques_sitio')).rows;
    const politicas=(await db.query("select schemaname,tablename,policyname,qual,with_check from pg_policies where tablename in ('productos','administradores','bloques_sitio','menu_sitio','configuracion_sitio') order by tablename,policyname")).rows;
    await db.exec(await readFile(new URL('../supabase/paginas-carrasco.sql',import.meta.url),'utf8'));
    const antes=(await db.query('select * from public.productos')).rows;
    const colores=(await db.query('select visual from public.configuracion_sitio')).rows;
    const cantidad=(await db.query('select count(*)::integer n from public.bloques_pagina')).rows[0].n;
    await db.exec(await readFile(new URL('../supabase/paginas-carrasco.sql',import.meta.url),'utf8'));
    assert.deepEqual((await db.query('select * from public.productos')).rows,antes);
    assert.deepEqual((await db.query('select visual from public.configuracion_sitio')).rows,colores);
    assert.equal((await db.query('select count(*)::integer n from public.bloques_pagina')).rows[0].n,cantidad);
    assert.deepEqual((await db.query('select * from public.bloques_sitio')).rows,anteriores);
    assert.deepEqual((await db.query("select schemaname,tablename,policyname,qual,with_check from pg_policies where tablename in ('productos','administradores','bloques_sitio','menu_sitio','configuracion_sitio') order by tablename,policyname")).rows,politicas);
    assert.equal((await db.query("select count(*)::integer n from public.bloques_pagina where datos->>'titulo'='Contenido anterior conservado'")).rows[0].n,1);
    async function rol(nombre,usuario='') {await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[usuario]);await db.exec('set role '+nombre);}
    await rol('authenticated',admin);
    const padre={id:crypto.randomUUID(),nombre:'Servicios',slug:'servicios',padre_id:null,sistema:'personalizada',orden:2,en_menu:true};
    const b={id:crypto.randomUUID(),tipo:'texto',titulo:'Texto publicado',ancla:'servicios-texto',visible:true,orden:0};
    const guardar=async(p,lista)=>db.query('select public.cms_guardar_pagina($1::jsonb,$2::jsonb)',[JSON.stringify(p),JSON.stringify(lista)]);
    const publicar=async id=>db.query('select public.cms_publicar_pagina($1::uuid)',[id]);
    await guardar(padre,[b,{...b,id:crypto.randomUUID(),titulo:'Bloque oculto privado',visible:false,orden:1}]);
    assert.equal((await db.query('select count(*)::integer n from public.paginas_publicadas where id=$1',[padre.id])).rows[0].n,0);
    await publicar(padre.id);
    assert.equal((await db.query('select bloques from public.paginas_publicadas where id=$1',[padre.id])).rows[0].bloques.length,1);
    const hija={id:crypto.randomUUID(),nombre:'Instalación',slug:'instalacion',padre_id:padre.id,sistema:'personalizada',orden:0,en_menu:true};
    await guardar(hija,[]);await publicar(hija.id);
    assert.equal((await db.query('select ruta from public.paginas_publicadas where id=$1',[hija.id])).rows[0].ruta,'/servicios/instalacion');
    await guardar({...padre,nombre:'Nuevo nombre en borrador',revision:1},[{...b,titulo:'Borrador privado'}]);
    const publicada=(await db.query('select nombre,bloques from public.paginas_publicadas where id=$1',[padre.id])).rows[0];
    assert.equal(publicada.nombre,'Servicios');assert.equal(publicada.bloques[0].titulo,'Texto publicado');
    await assert.rejects(()=>guardar({...padre,revision:1},[]),/otra sesión/);
    await assert.rejects(()=>guardar({...padre,revision:2,padre_id:hija.id},[]),/ciclo/);
    await rol('anon');
    assert.equal((await db.query('select count(*)::integer n from public.paginas_publicadas')).rows[0].n,4);
    await assert.rejects(()=>db.query('select * from public.paginas'),/permission denied/);
    await assert.rejects(()=>db.query('select * from public.bloques_pagina'),/permission denied/);
    await assert.rejects(()=>publicar(padre.id),/permission denied/);
    await rol('authenticated',admin);
    await db.query('select public.cms_ocultar_pagina($1::uuid)',[padre.id]);
    await rol('anon');
    assert.equal((await db.query('select count(*)::integer n from public.paginas_publicadas')).rows[0].n,2);
    await rol('authenticated',admin);
    await guardar({...padre,slug:'servicios-nuevos',revision:2},[b]);await publicar(padre.id);
    assert.equal((await db.query('select ruta from public.paginas_publicadas where id=$1',[hija.id])).rows[0].ruta,'/servicios-nuevos/instalacion');
    const copia=(await db.query('select public.cms_duplicar_pagina($1::uuid) id',[padre.id])).rows[0].id;
    assert.equal((await db.query('select count(*)::integer n from public.paginas_publicadas where id=$1',[copia])).rows[0].n,0);
    assert.equal((await db.query('select count(*)::integer n from public.bloques_pagina where pagina_id=$1',[copia])).rows[0].n,1);
    await rol('authenticated','20000000-0000-4000-8000-000000000001');
    assert.equal((await db.query('select * from public.paginas')).rows.length,0);
    await assert.rejects(()=>publicar(padre.id),/Solo administradores/);
    await assert.rejects(()=>guardar({...padre,revision:3},[]),/Solo administradores/);
    await rol('postgres');
    assert.deepEqual((await db.query('select * from public.productos')).rows,antes);
  } finally {await db.close();}
});
